### ISSUE TITLE
Did you remove slickHandle.slideIndex ?

### ISSUE THREAD

**Issue by manelephant** [kbdaitch/angular-slick-carousel#13]
Hello and thanx for the lib !

Can we still use slickHandle.slideIndex ? Because i can't make my code work for now.

My real problem is that i can use slickHandle.slickGoTo($index) inside a custom template (slickHandle belonging to another slick carousel).

The use case is two slick carousel : One for thumbs + one for large images

Cheers

**Comment by kbdaitch** [comment]
@manelephant I didn't remove any slickHandle methods. Check the version of slick you are using.

If you look at the current slick documentation, you can call any slick methods directly. Perhaps you can confirm to me, whether you are able to call the desired method that way?

But totally, this directive helps to reduce boilerplate by providing the handle. So if you think something is going wrong, please elaborate. I got a little confused about the title of the issue mentioning slideIndex, there has never been any such method.

If slickGoTo is working for one use case and not for the other, I would make sure, the both directive uses have appropriate attributes. Let me know.

**Comment by manelephant** [comment]
Thanx a lot for your response. I'll check my code & report if necessary.
