### ISSUE TITLE
Example with ajax items

### ISSUE THREAD

**Issue by FDiskas** [kbdaitch/angular-slick-carousel#19]
Needed an example with fetched items by ajax.

**Comment by kbdaitch** [comment]
@FDiskas the directive currently doesn't support dynamically changing the `media` attribute.

Please refer to my comment [here](https://github.com/kbdaitch/angular-slick-carousel/issues/8#issuecomment-63096304).

I have a plunkr that demonstrates the use case, linked in the same comment.
