### ISSUE TITLE
How to reinit the slider when item is added to ng-repeat?

### ISSUE THREAD

**Issue by daniel-obadia** [kbdaitch/angular-slick-carousel#8]
I see the "slickHandle.slickAdd" function is available, this seems to trigger a reinit on the slider.

However, in my case, I'm doing a $watch on my data and as soon as it changes I reloadData(newValue) in order to add the item to the ng-repeat.

This of course breaks the slider as a new item has been added without it reinitializing. 

Any idea how I could do this? Once more thanks for your amazing support!

**Comment by FDiskas** [comment]
I just extended the main slick directive 
```javascript
.directive('slick', ['$timeout', function ($timeout) {

            var isInitialized;
            return {
                //controller: 'teaserCtrl',
                link: function (scope, element, attr) {

                    // Get extended scope
                    var iScope = angular.element(element).isolateScope();

                    $timeout(function () {
                        isInitialized = false;

                        return iScope.$watch('media', function (newVal, oldVal) {

                            if (newVal !== null && newVal !== oldVal) {
                                if (isInitialized) {
                                    return element.slick('unslick');
                                }
                                $timeout(function () {
                                    iScope.init();
                                }, 100);

                                return isInitialized = true;
                            }
                        });
                    });
                }
            };

        }])
```

**Comment by fantaishao** [comment]
@charandas 
I refer to your method，but  there is  something wrong  with my code.
The console display that  _"TypeError: $scope.slickHandle.slickAdd is not a function"_

**Comment by fantaishao** [comment]
@FDiskas 
In my project , I show the carousel data through ng-repeat, update data through websocket.
And I follow the method like this changing my carousel
_https://github.com/devmark/angular-slick-carousel#slide-data_
But this way cause carousel blinking when the carousel update.

 Can you give me a small snippet of how you did this in your controller ,after extending  the main slick directive?

**Comment by FDiskas** [comment]
@fantaishao sorry. Not working on that project any more.
